import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const schemaPath = join(dirname(fileURLToPath(import.meta.url)), 'schema.prisma');
let schema = readFileSync(schemaPath, 'utf8');

// Relation name strings in @relation("...")
const relationNames: [string, string][] = [
  ['"note_note_note_idTonote"',       '"NoteAsChild"'],
  ['"note_note_parent_idTonote"',     '"NoteAsParent"'],
  ['"note_user_created_byTouser"',    '"NoteUserCreator"'],
  ['"note_user_user_idTouser"',       '"NoteUserMember"'],
  ['"userTouser"',                    '"UserCreator"'],
];

// Field names auto-generated by Prisma for ambiguous relations
const fieldNames: [string, string][] = [
  // Note model back-refs (longer names first, though none are substrings of each other)
  ['noteNoteNoteNoteNoteIdTonote',         'asChild'],     // NoteNote records where this Note is note_id
  ['noteNoteNoteNoteParentIdTonote',       'asParent'],    // NoteNote records where this Note is parent_id
  // NoteNote model FK fields
  ['noteNoteNoteNoteIdTonote',             'note'],        // the child note
  ['noteNoteNoteParentIdTonote',           'parent'],      // the parent note
  // NoteUser model FK fields
  ['userNoteUserCreatedByTouser',          'creator'],     // created_by → user
  ['userNoteUserUserIdTouser',             'member'],      // user_id → user
  // User model back-refs for NoteUser
  ['noteUserNoteUserCreatedByTouser',      'createdMemberships'],
  ['noteUserNoteUserUserIdTouser',         'memberships'],
  // User model self-ref back-ref
  ['otherUser',                            'createdUsers'],
];

for (const [from, to] of [...relationNames, ...fieldNames]) {
  schema = schema.replaceAll(from, to);
}

// Rename User's self-ref FK field: "user" → "creator"
// (must run after "userTouser" → "UserCreator" above)
schema = schema.replace(
  /\buser(\s+User\s+@relation\("UserCreator")/,
  'creator$1',
);

writeFileSync(schemaPath, schema);
