/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface File {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  data: Buffer;
  deletedAt: Timestamp | null;
  filename: string | null;
  id: Generated<string>;
  meta: Json | null;
  mime: string;
  seq: Generated<string>;
}

export interface Note {
  body: string | null;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  seq: Generated<string>;
  title: string | null;
}

export interface NoteNote {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  noteId: string;
  parentId: string;
  seq: Generated<string>;
}

export interface NoteReaction {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  noteId: string;
  reactionId: string;
  seq: Generated<string>;
}

export interface NoteTag {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  noteId: string;
  seq: Generated<string>;
  tagId: string;
}

export interface NoteUser {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  noteId: string;
  seq: Generated<string>;
  userId: string;
}

export interface Reaction {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  emoji: string;
  id: Generated<string>;
  meta: Json | null;
  name: string;
  seq: Generated<string>;
}

export interface Role {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  name: string;
  seq: Generated<string>;
}

export interface Tag {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  name: string;
  seq: Generated<string>;
}

export interface User {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  name: string | null;
  seq: Generated<string>;
  username: string;
}

export interface DB {
  file: File;
  note: Note;
  noteNote: NoteNote;
  noteReaction: NoteReaction;
  noteTag: NoteTag;
  noteUser: NoteUser;
  reaction: Reaction;
  role: Role;
  tag: Tag;
  user: User;
}
