/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface File {
  at: Generated<Timestamp>;
  by: string | null;
  data: Buffer;
  deletedAt: Timestamp | null;
  filename: string | null;
  id: Generated<string>;
  meta: Json | null;
  mime: string;
  seq: Generated<string>;
}

export interface Note {
  at: Generated<Timestamp>;
  body: string | null;
  by: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  seq: Generated<string>;
  title: string | null;
}

export interface Reaction {
  at: Generated<Timestamp>;
  by: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  name: string;
  seq: Generated<string>;
}

export interface Relation {
  at: Generated<Timestamp>;
  by: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  onFileId: string | null;
  onNoteId: string | null;
  onRelation: string | null;
  onRoleId: string | null;
  onTagId: string | null;
  onUserId: string | null;
  seq: Generated<string>;
  toFileId: string | null;
  toNoteId: string | null;
  toRelation: string | null;
  toRoleId: string | null;
  toTagId: string | null;
  toUserId: string | null;
}

export interface Role {
  at: Generated<Timestamp>;
  by: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  name: string;
  seq: Generated<string>;
}

export interface Tag {
  at: Generated<Timestamp>;
  by: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  name: string;
  seq: Generated<string>;
}

export interface User {
  at: Generated<Timestamp>;
  by: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  meta: Json | null;
  name: string | null;
  seq: Generated<string>;
  username: string;
}

export interface DB {
  file: File;
  note: Note;
  reaction: Reaction;
  relation: Relation;
  role: Role;
  tag: Tag;
  user: User;
}
