/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Entity {
  id: Generated<string>;
  meta: Json | null;
  seq: Generated<string>;
}

export interface File {
  at: Generated<Timestamp>;
  by: string | null;
  data: Buffer;
  deleted_at: Timestamp | null;
  filename: string | null;
  id: string;
  mime: string;
}

export interface Note {
  at: Generated<Timestamp>;
  body: string;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  title: string | null;
}

export interface Reaction {
  at: Generated<Timestamp>;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
}

export interface Relation {
  at: Generated<Timestamp>;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  on: string;
  to: string;
}

export interface Role {
  at: Generated<Timestamp>;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
}

export interface Tag {
  at: Generated<Timestamp>;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
}

export interface User {
  at: Generated<Timestamp>;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  username: string;
}

export interface DB {
  entity: Entity;
  file: File;
  note: Note;
  reaction: Reaction;
  relation: Relation;
  role: Role;
  tag: Tag;
  user: User;
}
