/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface File {
  at: Generated<Timestamp>;
  by: string | null;
  data: Buffer;
  deleted_at: Timestamp | null;
  filename: string | null;
  id: string;
  meta: Json | null;
  mime: string;
  seq: Generated<string>;
}

export interface Note {
  at: Generated<Timestamp>;
  body: string;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  meta: Json | null;
  seq: Generated<string>;
  title: string | null;
}

export interface Reaction {
  at: Generated<Timestamp>;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  meta: Json | null;
  name: string;
  seq: Generated<string>;
}

export interface Relation {
  at: Generated<Timestamp>;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  meta: Json | null;
  on_file_id: string | null;
  on_note_id: string | null;
  on_relation: string | null;
  on_role_id: string | null;
  on_tag_id: string | null;
  on_user_id: string | null;
  seq: Generated<string>;
  to_file_id: string | null;
  to_note_id: string | null;
  to_relation: string | null;
  to_role_id: string | null;
  to_tag_id: string | null;
  to_user_id: string | null;
}

export interface Role {
  at: Generated<Timestamp>;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  meta: Json | null;
  name: string;
  seq: Generated<string>;
}

export interface Tag {
  at: Generated<Timestamp>;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  meta: Json | null;
  name: string;
  seq: Generated<string>;
}

export interface User {
  at: Generated<Timestamp>;
  by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  meta: Json | null;
  seq: Generated<string>;
  username: string;
}

export interface DB {
  file: File;
  note: Note;
  reaction: Reaction;
  relation: Relation;
  role: Role;
  tag: Tag;
  user: User;
}
